ch=input()
if(ch=='V'):
    print("Violet")
elif(ch=='I'):
    print("Indigo")
elif(ch=='B'):
    print("Blue")
elif(ch=='G'):
    print("Green")
elif(ch=='Y'):
    print("Yellow")
elif(ch=='O'):
    print("Orange")
elif(ch=='R'):
    print("Red")
else:
    print("-1")